alert("Hey, This is Sakshi. Nice to have you visit my page ");

//shortcut for console: CTRL+ SHIFT + J

//each instuction is called a statement in JS

console.log(" ! STOP  SNOOPING !"); //shows in console

document.write('Hello there Stranger !'); //display onscreen of any webpage

let numberOfCats; //variables 

const name = "SAKSHI"; //NON-changable

toFixed(""); //to round 2 decimals

//function : reusable 
function catFacts(numberOfCats) {
    Alert("ALERT");

    console.log("KITTIES" + numberOfCats);
}
catFacts(4);